resources:
- name: bosh-softlayer-tools
  type: git
  source:
    uri: https://github.com/zhanggbj/bosh-softlayer-tools.git
    branch: WIP-ci

- name: version-semver
  type: semver
  source:
    key:               current-version
    bucket:            {{s3_pipeline_bucket}}
    access_key_id:     {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

jobs:
- name: bmp-unit
  public: true
  plan:
  - get: bosh-softlayer-tools
    trigger: true
  - task: unit
    file: bosh-softlayer-tools/ci/bmp-unit.yml
    config:
      params:
        SL_USERNAME: fake-username
        SL_API_KEY: fake-api-key

- name: bmp-integration
  plan:
  - get: bosh-softlayer-tools
    trigger: true
    passed: [bmp-unit]
  - task: integration
    file: bosh-softlayer-tools/ci/bmp-integration.yml
    config:
      params:
        TARGET_URL: {{TARGET_URL}}
        BMP_USERNAME: {{BMP_USERNAME}}
        BMP_PASSWORD: {{BMP_PASSWORD}}

- name: bmp-promote
  plan:
  - get: bosh-softlayer-tools
    trigger: true
    passed: [bmp-integration]
  - task: integration
    file: bosh-softlayer-tools/ci/bmp-promote.yml
    config:
      params:
        S3_ACCESS_KEY_ID: {{s3_access_key__primary}}
        S3_SECRET_ACCESS_KEY: {{s3_secret_key__primary}}

groups:
- name: bosh-softlayer-tools
  jobs:
  - bmp-unit
  - bmp-integration
  - bmp-promote



