---
platform: linux
image: docker:///cloudfoundry/bosh-lite-ci

inputs:
  - name: bosh-softlayer-tools
    path: gopath/src/github.com/cloudfoundry-community/bosh-softlayer-tools
  - name: version-semver

outputs:
  - name: promoted

run:
  path: gopath/src/github.com/cloudfoundry-community/bosh-softlayer-tools/ci/tasks/bst-promote.sh