---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-lite-ci

inputs:
  - name: bosh-softlayer-tools
    path: gopath/src/github.com/cloudfoundry-community/bosh-softlayer-tools
  - name: stemcell-info
  - name: stemcell-version
  - name: candidate-stemcell-ubuntu-trusty
outputs:
  - name: new-light-stemcell

run:
  path: gopath/src/github.com/cloudfoundry-community/bosh-softlayer-tools/ci/tasks/create-light-stemcell
