---
platform: linux
image: docker:///cloudfoundry/bosh-lite-ci
inputs:
  - name: stemcell-version
  - name: bosh-softlayer-tools
  - name: stemcell-ubuntu-trusty-raw
outputs:
  - name: build
run:
  path: bosh-softlayer-tools/ci/tasks/generate-bm-stemcell-fsa.sh
