resources:
- name: bosh-softlayer-tools
  type: git
  source:
    uri: https://github.com/zhanggbj/bosh-softlayer-tools.git
    branch: security-ppl

- name: version-semver
  type: semver
  source:
    key:               current-version
    bucket:            {{s3_bosh_softlayer_tools_bucket}}
    access_key_id:     {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: bosh-softlayer-tools-artifacts
  type: s3
  source:
    regexp: bosh-softlayer-tools-([0-9.]+)\.tgz
    bucket: {{s3_bosh_softlayer_tools_bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: light-stemcell
  type: s3
  source:
    regexp: light-bosh-stemcell-([0-9.]+)-softlayer-xen-ubuntu-trusty-go_agent\.tgz
    bucket: {{s3_bluemix_stemcell_bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

jobs:
- name: upgrade-stemcell
  public: true
  plan:
  - aggregate:
      - {trigger: true, get: stemcell, resource: light-stemcell}
      - {trigger: false, get: bosh-softlayer-tools, resource: bosh-softlayer-tools}

  - task: upgrade-stemcell
    file: bosh-softlayer-tools/ci/tasks/upgrade-stemcell.yml
    config:
      params:
        BLUEMIX_DIRECTOR_IP: {{bluemix_director_ip}}
        BOSH_CLI: {{bosh_cli}}
        BOSH_CLI_PASSWORD: {{bosh_cli_password}}

- name: verify-security-release
  public: true
  plan:
  - aggregate:
      - {trigger: false, passed: [upgrade-stemcell], get: bosh-softlayer-tools, resource: bosh-softlayer-tools}

  - task: verify-security-release
    file: bosh-softlayer-tools/ci/tasks/verify-security-release.yml
    config:
      params:
        BLUEMIX_DIRECTOR_IP: {{bluemix_director_ip}}
        BOSH_CLI: {{bosh_cli}}
        BOSH_CLI_PASSWORD: {{bosh_cli_password}}

#- name: bst-integration
#  plan:
#  - get: bosh-softlayer-tools
#    trigger: true
#    passed: [bst-unit]
#
#  - task: bst-integration
#    file: bosh-softlayer-tools/ci/tasks/bst-integration.yml
#    config:
#      params:
#        TARGET_URL: {{TARGET_URL}}
#        BMP_USERNAME: {{BMP_USERNAME}}
#        BMP_PASSWORD: {{BMP_PASSWORD}}
#
#- name: bst-promote-build
#  plan:
#  - aggregate:
#      - {trigger: false, get: version-semver, params: {bump: patch}, resource: version-semver}
#
#  - get: bosh-softlayer-tools
#    trigger: true
#    passed: [bst-integration]
#
#  - task: bst-promote-build
#    file: bosh-softlayer-tools/ci/tasks/bst-promote.yml
#    config:
#      params:
#        S3_ACCESS_KEY_ID: {{s3_access_key__primary}}
#        S3_SECRET_ACCESS_KEY: {{s3_secret_key__primary}}
#
#  - put: version-semver
#    params: {file: version-semver/number}
#
#  - put: bosh-softlayer-tools-artifacts
#    params: {from: promoted/.*\.tgz}
#
#groups:
#- name: bosh-softlayer-tools
#  jobs:
#  - bst-unit
#  - bst-integration
#  - bst-promote-build
